### ISSUE TITLE
Boolean.getBoolean does not work for me. Only Boolean.valueOf

### ISSUE THREAD

**Issue by sharapov** [SubZane/JIniFile#1]

**Comment by sharapov** [comment]
Thank you for your work :)

**Comment by jon-mil-92** [comment]
I came to this conclusion as well! I was scratching my head for a good hour while sifting through my code only to discover this issue in the JIniFile class! I really should have read the comments before integrating this into my project lol.

**Comment by SubZane** [comment]
if you can fixed that an do a PR that would be great. I stopped writing java-code about 20 years ago and just published this in case someone found it useful :)

**Comment by jon-mil-92** [comment]
> if you can fixed that an do a PR that would be great. I stopped writing java-code about 20 years ago and just published this in case someone found it useful :)

Pull request sent :)

**Comment by SubZane** [comment]
merged (finally...sorry, I'm slow)
